### ISSUE TITLE
Looking good , one minor bug 

### ISSUE THREAD

**Issue by SerpentDrago** [SwagOtaku/plugin.video.kaito#1]
Once you pick a  show and pick a season 

If you ever go to that show again , it won't let you pick a season. just goes to the last season picked. 

I see no context menu option or any setting to Stop this . Even setting content type to tvshow doesn't fix .  could be a hold over from seren's auto episode resume where picking a show will auto remember and play from last season you watched . just a random guess though. 

I sent you a message on reddit concerning PM , check it . thanks :)

**Comment by SwagOtaku** [comment]
This is intended because at the season selection page the addon is going from anilist anime metadata to fetch trakt/tmdb episodes metadata of the selected season. So when you pick the season it gets attached to that show. 

For example, if you want to get Boku no Hero Academia Season 2, you would select Boku no Hero Acadmia Season 2 (anilist) > season page S2 (trakt). If you happen to choose the wrong season or the addon gives you a totally different show's season you can use the context menu 'Season Correction' to correct it

**Comment by SerpentDrago** [comment]
Thats kinda awful design , no offence, seriously just being honest  . is there no other method you can do that ? i fully get if you can't , just trust me i'm not going to be the only one seeing this as a pretty major issue . 

I thought i had looked at the context menu , but must have missed it .

**Comment by SwagOtaku** [comment]
@SerpentDrago updated the addon with a new method that auto selects the correct season (based on the year season aired) and only falls back on season selection page if the addon can't find/choose right season. Let me know what you think
