### ISSUE TITLE
Work around for fios users

### ISSUE THREAD

**Issue by dunnhole** [SwagOtaku/plugin.video.kaito#89]
Is there any workaround we can do to add another scraper or fork for nyaa that will work for verizon users.

**Comment by Goldenfreddy0703** [comment]
oh dear, im so sorry your provider is verizon, you might be better off using a vpn in order to get a workaround on that or by switching to T mobile, you could basically do anything of course as long as you have real debrid.
![image](https://user-images.githubusercontent.com/62456796/134714724-ecc59547-5d6f-460d-9ed7-49e92f5686dc.png)

**Comment by dunnhole** [comment]
I have real debrid, but I was also wondering if I switched to premiumize would it work.  I see that premiumize comes with VPN services, has anyone tried?  Can anyone confirm it would work before I switch my services over to them.  I can switch back to my other service provider, I was not aware verizon did this.  I switched because Verizon had better services, faster speeds and was cheaper.  Just want to see if thier are any workarounds before going through the hassle of switching.

**Comment by Goldenfreddy0703** [comment]
if i were me, i would stick with real debrid cause premiumize has issues from what i herd i never used premiumize before cause i have a provider with super fast internet that does not track what i do. If i were you, instead of going through the hassle of switching, you might want to consider finding a vpn service like nordvpn. if you have a router that can be customized or a router where you can change the dns to static then you should be able to setup a vpn service in your home in order to bypass Verizon. Btw yes verizon has faster speed but its kinda expensive from what i herd, sticking with T Mobile as long as you got 5g would probably be a better option.

**Comment by dunnhole** [comment]
You can close this out, I ended up using zomboided vpn manager to set up ipvanish and am now able to scrape nyaa again while still on Verizon fios.
